[project]
name = "pythonproject-studio-inventory"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib==3.10.8",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "pdfplumber>=0.11.9",
    "python-dotenv>=1.2.1",
    "reportlab>=4.4.9",
    "requests>=2.32.5",
    "requests-pkcs12>=1.27",
    "typer>=0.21.1",
]
